### ISSUE TITLE
Write tests to bring up code coverage in jaeger-jaxrs2 and jaeger-dropwizard

### ISSUE THREAD

**Issue by oibe** [uber/jaeger-client-java#11]
Especially:
/jaeger-jaxrs2/src/main/java/com/uber/jaeger/filters/jaxrs2/TracingUtils.java
/jaeger-jaxrs2/src/main/java/com/uber/jaeger/filters/jaxrs2/Constants.java
 /jaeger-jaxrs2/src/main/java/com/uber/jaeger/filters/jaxrs2/TracingUtils.java
 /jaeger-jaxrs2/src/main/java/com/uber/jaeger/filters/jaxrs2/ServerFilter.java

**Comment by yurishkuro** [comment]
Closing in favor of #182
