### ISSUE TITLE
Add error-prone to the build

### ISSUE THREAD

**Issue by yurishkuro** [uber/jaeger-client-java#114]
E.g. https://github.com/openzipkin/zipkin/pull/1446/files#diff-2

**Comment by adriancole** [comment]
this is already there :P just needs a upgrade.

**Comment by vprithvi** [comment]
@yurishkuro We already use https://github.com/tbroyer/gradle-errorprone-plugin to run error prone in our build. The plugin is configured to use the latest release version of errorprone. 

Is there something in our code that error prone should have caught that slipped through?

**Comment by yurishkuro** [comment]
+1
