### ISSUE TITLE
Update .gitignore 

### ISSUE THREAD

**Issue by nklmish** [uber/jaeger-client-java#12]
When we import the project into IDE (e.g. IntelliJ, Eclipse, NetBeans), some IDE specific files are generated, which we need to ignore. 

The same applies to Operating system specific files. E.g. on mac *.DS_Store, . LSOverride, etc.

We can extend our .gitignore file to cover some more defaults?

**Comment by yurishkuro** [comment]
@nklmish feel free to do a pull request with the changes you want.

**Comment by nklmish** [comment]
Merged https://github.com/uber/jaeger-client-java/pull/13
