### ISSUE TITLE
Java 6 compatibility

### ISSUE THREAD

**Issue by felixbarny** [uber/jaeger-client-java#129]
Hi,

it would be nice if Jaeger was Java 6 compatible as I want to use it for stagemonitor, which currently is Java 6 compatible. Are there any reasons you don't want to support Java 6?

Cheers,
Felix

**Comment by yurishkuro** [comment]
I have no objections. I assume there's no performance degradation from running on bytecode generated by v6 vs. v7. And I don't think we're using any special features / APIs.

Can you submit a PR?

**Comment by felixbarny** [comment]
Yes, I can do this.
