### ISSUE TITLE
Add B3TextMapCodec to jaeger-core

### ISSUE THREAD

**Issue by felixbarny** [uber/jaeger-client-java#136]
As B3 context propagation is not Zipkin specific, it would be nice if B3TextMapCodec was included in jaeger-core.

**Comment by yurishkuro** [comment]
it is not a requirement for Core, why do we want it there? If people need B3 they can include jaeger-zipkin.

**Comment by felixbarny** [comment]
But that also pulls in a large set of unneeded dependencies. If it was in core people can decide to use b3 propagation rather than the jaeger specific one which plays together more nicely with other non-jaeger-traced services.

**Comment by yurishkuro** [comment]
if they other services are not jaeger-traced, they are not using jaeger-backend either, so wouldn't you need zipkin reporting as well?

**Comment by felixbarny** [comment]
> if they other services are not jaeger-traced, they are not using jaeger-backend either, so wouldn't you need zipkin reporting as well?

Not if they use a different (maybe custom) backend but also use B3 for context propagation.

To add some background, I'm currently trying to make stagemonitor as independent from the underlying OT impl as possible. So that swapping out the implementation is as easy as possible. This however requires all implementations to use the same propagation format. B3 is the obvious choice here as it is used most widely.

Also, I need to be able to get ahold of the traceId, spanId and parantId in an impl independent way. This can also be achieved by injecting the B3 headers into a `Map` and `get`ting the IDs via the well known B3 header names.

**Comment by yurishkuro** [comment]
Well, I still don't like putting B3 into core. I think the cleanest solution is to build/release an extra jar in the jaeger-zipkin module, e.g. jaeger-zipkin-b3.

Let me check with the team if we have any pending work. I think we should be ready to release 0.18

**Comment by adriancole** [comment]
Fwiw there most certainly are non zipkin B3 systems not just internal. For
example cloud foundry router uses B3 but does not report to zipkin at all.
It uses log scraping approach for PCF metrics which shares no code or
architecture with zipkin. Same thing for nike wingtips. There are other
zipkin clones that use B3 as well if need be I can list the non internal
ones. This is why we made the b3-propagation repo btw..

jaeger-b3 here is probably the right name. We have a repo b3-propagation so
if apis are stable we could publish adapter there too... like b3-jaeger ;)

**Comment by adriancole** [comment]
The problem with publishing externally is that the trace context might
change here and then require coordinated updates. Also there havent been
others asking.. another option is to manually exclude the zipkin
dependencies as they arent likely used for inject extract iirc.

**Comment by felixbarny** [comment]
zipkin.internal.Util is used

**Comment by adriancole** [comment]
>
> zipkin.internal.Util is used
>
I could patch to make that go away.. would that be worthwhile? Ex brave has
HexCodec for this and it would be 86 lines of rarely ever change code
copy/pasted (with tests)

**Comment by adriancole** [comment]
or.. we could shade that class from zipkin

**Comment by felixbarny** [comment]
Do you mean shading manually (aka copy pasta) or is it possible to shade just one class with the gradle shade plugin?

**Comment by adriancole** [comment]
>
> Do you mean shading manually (aka copy pasta) or is it possible to shade
> just one class with the gradle shade plugin?
>
not sure what gradle supports, but I've done cherry-pick shading in the
past with maven:

https://github.com/openzipkin/zipkin/blob/master/zipkin/pom.xml#L100

either way, though. it isn't much code and the code in question (hex codec)
is quite stable.

**Comment by felixbarny** [comment]
In the mean time I shaded the B3 class into stagemonitor. It feels like a work around and I'd prefer the B3 class to be in jaeger-core or jaeger-b3 but I'd be ok with it.

@yurishkuro how would you like to proceed?

**Comment by yurishkuro** [comment]
Can you do a pr to build an extra jaeger-b3 jar in the jaeger-zipkin module? Or move to a separate module if that's easier. 

I think one format we'd want to support in core will be github.com/tracecontext

**Comment by adriancole** [comment]
https://github.com/uber/jaeger-client-java/pull/141
