### ISSUE TITLE
Fix compile warnings on JaegerThriftSpanConverterTest

### ISSUE THREAD

**Issue by kevinearls** [uber/jaeger-client-java#165]
When building I get the following warnings:

/home/kearls/tmp/jaeger-client-java/jaeger-core/src/test/java/com/uber/jaeger/reporters/protocols/JaegerThriftSpanConverterTest.java:62: warning: [BoxedPrimitiveConstructor] valueOf or autoboxing provides better time and space performance
        { new Long(1), TagType.LONG, new Long(1) },
          ^
    (see http://errorprone.info/bugpattern/BoxedPrimitiveConstructor)
  Did you mean '{ (long) 1, TagType.LONG, new Long(1) },'?
/home/kearls/tmp/jaeger-client-java/jaeger-core/src/test/java/com/uber/jaeger/reporters/protocols/JaegerThriftSpanConverterTest.java:62: warning: [BoxedPrimitiveConstructor] valueOf or autoboxing provides better time and space performance
        { new Long(1), TagType.LONG, new Long(1) },
                                     ^
    (see http://errorprone.info/bugpattern/BoxedPrimitiveConstructor)
  Did you mean '{ new Long(1), TagType.LONG, (long) 1 },'?
/home/kearls/tmp/jaeger-client-java/jaeger-core/src/test/java/com/uber/jaeger/reporters/protocols/JaegerThriftSpanConverterTest.java:63: warning: [BoxedPrimitiveConstructor] valueOf or autoboxing provides better time and space performance
        { new Integer(1), TagType.LONG, new Long(1) },
          ^
    (see http://errorprone.info/bugpattern/BoxedPrimitiveConstructor)
  Did you mean '{ 1, TagType.LONG, new Long(1) },'?
/home/kearls/tmp/jaeger-client-java/jaeger-core/src/test/java/com/uber/jaeger/reporters/protocols/JaegerThriftSpanConverterTest.java:63: warning: [BoxedPrimitiveConstructor] valueOf or autoboxing provides better time and space performance
        { new Integer(1), TagType.LONG, new Long(1) },
                                        ^
    (see http://errorprone.info/bugpattern/BoxedPrimitiveConstructor)
  Did you mean '{ new Integer(1), TagType.LONG, (long) 1 },'?
/home/kearls/tmp/jaeger-client-java/jaeger-core/src/test/java/com/uber/jaeger/reporters/protocols/JaegerThriftSpanConverterTest.java:64: warning: [BoxedPrimitiveConstructor] valueOf or autoboxing provides better time and space performance
        { new Short((short) 1), TagType.LONG, new Long(1) },
          ^
    (see http://errorprone.info/bugpattern/BoxedPrimitiveConstructor)
  Did you mean '{ (short) 1, TagType.LONG, new Long(1) },'?
/home/kearls/tmp/jaeger-client-java/jaeger-core/src/test/java/com/uber/jaeger/reporters/protocols/JaegerThriftSpanConverterTest.java:64: warning: [BoxedPrimitiveConstructor] valueOf or autoboxing provides better time and space performance
        { new Short((short) 1), TagType.LONG, new Long(1) },
                                              ^
    (see http://errorprone.info/bugpattern/BoxedPrimitiveConstructor)
  Did you mean '{ new Short((short) 1), TagType.LONG, (long) 1 },'?
/home/kearls/tmp/jaeger-client-java/jaeger-core/src/test/java/com/uber/jaeger/reporters/protocols/JaegerThriftSpanConverterTest.java:65: warning: [BoxedPrimitiveConstructor] valueOf or autoboxing provides better time and space performance
        { new Double(1), TagType.DOUBLE, new Double(1) },
          ^
    (see http://errorprone.info/bugpattern/BoxedPrimitiveConstructor)
  Did you mean '{ (double) 1, TagType.DOUBLE, new Double(1) },'?
/home/kearls/tmp/jaeger-client-java/jaeger-core/src/test/java/com/uber/jaeger/reporters/protocols/JaegerThriftSpanConverterTest.java:65: warning: [BoxedPrimitiveConstructor] valueOf or autoboxing provides better time and space performance
        { new Double(1), TagType.DOUBLE, new Double(1) },
                                         ^
    (see http://errorprone.info/bugpattern/BoxedPrimitiveConstructor)
  Did you mean '{ new Double(1), TagType.DOUBLE, (double) 1 },'?
/home/kearls/tmp/jaeger-client-java/jaeger-core/src/test/java/com/uber/jaeger/reporters/protocols/JaegerThriftSpanConverterTest.java:66: warning: [BoxedPrimitiveConstructor] valueOf or autoboxing provides better time and space performance
        { new Float(1), TagType.DOUBLE, new Double(1) },
          ^
    (see http://errorprone.info/bugpattern/BoxedPrimitiveConstructor)
  Did you mean '{ (float) 1, TagType.DOUBLE, new Double(1) },'?
/home/kearls/tmp/jaeger-client-java/jaeger-core/src/test/java/com/uber/jaeger/reporters/protocols/JaegerThriftSpanConverterTest.java:66: warning: [BoxedPrimitiveConstructor] valueOf or autoboxing provides better time and space performance
        { new Float(1), TagType.DOUBLE, new Double(1) },
                                        ^
    (see http://errorprone.info/bugpattern/BoxedPrimitiveConstructor)
  Did you mean '{ new Float(1), TagType.DOUBLE, (double) 1 },'?
/home/kearls/tmp/jaeger-client-java/jaeger-core/src/test/java/com/uber/jaeger/reporters/protocols/JaegerThriftSpanConverterTest.java:67: warning: [BoxedPrimitiveConstructor] valueOf or autoboxing provides better time and space performance
        { new Byte((byte) 1), TagType.STRING, "1" },
          ^
    (see http://errorprone.info/bugpattern/BoxedPrimitiveConstructor)
  Did you mean '{ (byte) 1, TagType.STRING, "1" },'?
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
11 warnings

**Comment by black-adder** [comment]
#166
