### ISSUE TITLE
RemoteReporter throws exception when commandQueue is full

### ISSUE THREAD

**Issue by mabn** [uber/jaeger-client-java#178]
RemoteReporter uses ArrayBlockingQueue to store commands, but adding new commands is done with `ArrayBlockingQueue.add(x)` method which:

>Inserts the specified element into this queue if it is possible to do so immediately without violating capacity restrictions, returning true upon success and throwing an IllegalStateException if no space is currently available. When using a capacity-restricted queue, it is generally preferable to use offer.

Right now `RemoteReporter.report` checks if queue is full but it is not thread-safe.

It would be better to avoid `IllegalStateException` by using `RemoteReporter.offer(x)`, and if it fails (returns false) increment `reporterDropped` metric.

New version:
```
  public void report(Span span) {
    // Its better to drop spans, than to block here
    boolean added = commandQueue.offer(new AppendCommand(span));
    if(!added) {
        metrics.reporterDropped.inc(1);
    }
  }
```
The other `adds` should also `offer` instead.

**Comment by yurishkuro** [comment]
Fixed by #180 

Thanks, @mabn
