### ISSUE TITLE
Release 0.19.0

### ISSUE THREAD

**Issue by pavolloffay** [uber/jaeger-client-java#190]
Could we release 0.19.0 soon?

**Comment by yurishkuro** [comment]
Yes. We need to prep a PR to update the changelog with the list of changes since 0.18

**Comment by yurishkuro** [comment]
Released. May take a while to show up on central.

**Comment by pavolloffay** [comment]
It's there https://search.maven.org/#artifactdetails%7Ccom.uber.jaeger%7Cjaeger-core%7C0.19.0%7Cjar , thanks!
