### ISSUE TITLE
missing spans with asynchronous handlers

### ISSUE THREAD

**Issue by sweatybridge** [uber/jaeger-client-java#193]
I'm a student from Imperial College London working on a tracer project. I'm trying to benchmark Jaeger with my own little tracer and there seems to be a strange problem with missing spans.

My setup is to have one `app` service make three asynchronous calls to another `mockdb` service. Both services are written as Java Spring Boot applications using OpenTracing's auto-configuration (link to their [project](https://github.com/opentracing-contrib/java-spring-web)). The `mockdb` service runs an instrumented method 100 times which means I should be expecting 3 x 100 spans on the Jaeger UI. However, I'm getting only 200 spans as shown in the [screenshot](https://www.dropbox.com/s/9wz3mis6xsp88th/screencapture-graphic12-doc-ic-ac-uk-16686-search-1496612647094.png?dl=0).

Here's the link to the source code of my [benchmark application](https://github.com/sweatybridge/spring-jaeger).

Appreciate your help!

**Comment by yurishkuro** [comment]
First, can you enable span logging (ReporterConfig in the main configuration of the tracer) and confirm that your application code actually reports 300 spans to the tracer?

**Comment by sweatybridge** [comment]
Thank you for your prompt reply :)

I followed your advice and enabled span logging by setting its environment variable. I counted the number of lines of "Span reported" in `mockdb` logs. The output is below.

```
docker service logs tracer_mockdb | grep "Span reported" | wc -l
306
```

I suppose this means that 300 spans are reported to the tracer. The UI still shows some missing spans though.

**Comment by yurishkuro** [comment]
Ok next question - is your app exiting as soon as it finishes the work? The tracer batches spans in memory up to a packet of 65000 bytes, and you don't seem to call tracer.close() anywhere, so it may not have the time to send them out. A simple way to verify it is to put a sleep after the top level span is finished. Better is to call tracer.close() as part of the app shutdown sequence.

**Comment by sweatybridge** [comment]
I think tracer.close() is called for me automatically using Java 7's try-with-resources statement (https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html). Otherwise the compiler would emit a warning saying that io.opentracing.Span is not autocloseable (which it is because it implements Closeable).

Also I'm not shutting down the app after a single request. I can call the endpoint multiple times and they are seem to be around a hundred spans short.

**Comment by pavolloffay** [comment]
@sweatybridge you can also try your instrumentation run with `MockTracer` from `opentracing-mock` to see whether there is an issue with Jaeger tracer or the instrumentation.

**Comment by sweatybridge** [comment]
@pavolloffay appreciate your attention :). Do you have any examples of integrating MockTracer into a Spring Boot integration test? I'm not very familiar with how the mock beans are autowired...

**Comment by sweatybridge** [comment]
This is quite interesting. I've pushed new branch that contains my test setup (https://github.com/sweatybridge/spring-jaeger/tree/test/mock_tracer). The results is as follows.

```
tracer_mockdb.1.vn2gnegklctn@cloud-vm-47-141    | extract(Builtin.HTTP_HEADERS, io.opentracing.contrib.web.servlet.filter.HttpServletRequestExtractAdapter@35d44843)
tracer_mockdb.1.vn2gnegklctn@cloud-vm-47-141    | extract(Builtin.HTTP_HEADERS, io.opentracing.contrib.web.servlet.filter.HttpServletRequestExtractAdapter@3e6ad358)
tracer_mockdb.1.vn2gnegklctn@cloud-vm-47-141    | collected spans: 158
tracer_mockdb.1.vn2gnegklctn@cloud-vm-47-141    | collected spans: 202
tracer_mockdb.1.vn2gnegklctn@cloud-vm-47-141    | extract(Builtin.HTTP_HEADERS, io.opentracing.contrib.web.servlet.filter.HttpServletRequestExtractAdapter@db89921)
tracer_mockdb.1.vn2gnegklctn@cloud-vm-47-141    | collected spans: 305
```

I think the reason that we see 158 spans collected after serving the first request is because of asynchronous handling of those requests. The count is simply a cumulative sum. Is there anything else that you think could be a problem?

**Comment by pavolloffay** [comment]
@sweatybridge MockTracer can be also initialized with text map propagator, the default constructor does not register any injector/extractor. Another thing is that you can get all finished spans from MockTracer.

**Comment by sweatybridge** [comment]
Hmm so how can I know for sure that it isn't a problem with my instrumentation but with Jaeger tracer?

**Comment by black-adder** [comment]
Hi, the java client has a default max queue size of 100 spans (https://github.com/uber/jaeger-client-java/blob/master/jaeger-core/src/main/java/com/uber/jaeger/Configuration.java#L280) my guess is that you're creating more spans than the client is defaulted to handle. Do you mind trying to up the queue size and running again? We can take a deeper look if you still see the same issues.

**Comment by sweatybridge** [comment]
@black-adder Yes! That was indeed the problem. Thank you so much for your help!

**Comment by black-adder** [comment]
Gonna close this now, @sweatybridge keep in touch and let us know how the benchmarks go.
