### ISSUE TITLE
does jaeger have plan to support grpc?

### ISSUE THREAD

**Issue by ccl0326** [uber/jaeger-client-java#196]
We want to use jaeger as our uniform technology stack for multiple languages. but in
 our technology stack we use grpc. so i want to know do we have a plan to support it? if not, we glade to implement it.

**Comment by pavolloffay** [comment]
What do you exactly mean by grpc? For tracing grpc there is already OpenTracing integration https://github.com/grpc-ecosystem/grpc-opentracing/tree/master/java.

**Comment by ccl0326** [comment]
yep, i know there is some OpenTracing integration project already.
but we want a uniform technology stack for multiple languages. we'd better use a solution for multiple languages, so we can get some benefit likes uniform plan.

**Comment by yurishkuro** [comment]
Jaeger has fully supported OpenTracing libraries in Go, Java, Python, and Node.js, and more are on the way. This languages  support is independent of the question of RPC frameworks you use in your architecture - as long as the framework has OpenTracing instrumentation you can plug in Jaeger tracers to it. Jaeger itself does not instrument the the frameworks.

**Comment by ccl0326** [comment]
@yurishkuro I got it.Thanks.I will close this issue.
