### ISSUE TITLE
Signing task fails when performing local build

### ISSUE THREAD

**Issue by objectiser** [uber/jaeger-client-java#202]
When doing a local build on master, I am getting the following error:

> Execution failed for task ':jaeger-apachehttpclient:signArchives'.
Cannot perform signing task ':jaeger-apachehttpclient:signArchives' because it has no configured signatory

**Comment by jpkrohling** [comment]
A solution could be wrap the `signing` plugin definition within a conditional, like this:

```
if (project.hasProperty("signing.keyId")) {
    apply plugin: 'signing'
    signing {
        sign configurations.archives
    }
}
```

**Comment by objectiser** [comment]
Issue was caused because I was trying to set a release version (0.20.0), which caused the signing tasks to become activated.
