### ISSUE TITLE
jaeger-thrift no src?

### ISSUE THREAD

**Issue by candyleer** [uber/jaeger-client-java#213]
why jaeger-thrift folder don't contain  src (sources) ?not open-source?

**Comment by objectiser** [comment]
The source code for that module is automatically generated as part of the build.

**Comment by vprithvi** [comment]
The build pulls it in from [jaeger-idl](https://github.com/uber/jaeger-idl) repo and configures the compile task [here](https://github.com/uber/jaeger-client-java/blob/master/jaeger-thrift/build.gradle#L20).

**Comment by yurishkuro** [comment]
Added readme: https://github.com/uber/jaeger-client-java/commit/8784904110dda7a7c8a3ffb02541dcc76aa45c38
