### ISSUE TITLE
Enable Tracer tags to be specified via environment

### ISSUE THREAD

**Issue by objectiser** [uber/jaeger-client-java#214]
It is possible to create a Tracer using configuration obtained from environment variables, as outlined in the https://github.com/uber/jaeger-client-java/blob/master/jaeger-core/README.md.

However it is not currently possible to supply Tracer level (process) tags using this mechanism.

Proposal is to enable a list of tags to be provided as follows:

> JAEGER_TAGS = tag1:value1, tag2:${OTHER_ENV_VAR:default}

**Comment by black-adder** [comment]
sounds reasonable to me
