### ISSUE TITLE
question about data retention period in cassandra

### ISSUE THREAD

**Issue by fandan-nyc** [uber/jaeger-client-java#227]
Hi team, quick question. 
for the tracing data written in cassandra, is there a retention period ? 
I do not see any purge job which deprecates the data after certain time. 
just wondering if I miss any existing purge job (or anything similar) or that is on the to-do list or we have to implement the job by ourselves. 

look forward to the reply!

thanks a lot !
Dan

**Comment by black-adder** [comment]
If you used https://github.com/uber/jaeger/blob/master/plugin/storage/cassandra/schema/create.sh to initialize the keyspace, it defaults the TTL for everything to 2 days.

**Comment by vprithvi** [comment]
Hi Dan,

Cassandra supports TTLs, which we utilize in our schema. See https://github.com/uber/jaeger/blob/ec6378a7a5094ff3019c506163108da29f3f2f99/plugin/storage/cassandra/schema/create.sh#L11 for defaults.

**Comment by fandan-nyc** [comment]
thank you guys, this is super helpful !
