### ISSUE TITLE
It is possible to report invalid spans (endpoint.serviceName == null)

### ISSUE THREAD

**Issue by adriancole** [uber/jaeger-client-java#45]
In zipkin's thrift, Endpoint.serviceName is not an optional field. Conventionally, some set this to empty, but not serializing it is a mistake. I noticed this when using the jersey client, which might hint there's a bug there (as I did specify a serviceName).

This should be enforced in unit tests or similar as otherwise the only way to know is after it reaches zipkin.

**Comment by adriancole** [comment]
The workaround I'm using now is the following in Span.java

```
peer = new Endpoint().setService_name("");
```

**Comment by yurishkuro** [comment]
Would #46 fix it?  Or is this for some other endpoint, e.g. when not setting `peer.serviceName

**Comment by adriancole** [comment]
I don't think it should be required to assign peer.serviceName, btw.. if
that's empty, then just don't log a binary annotation. If it is required,
then probably docs would help (ex. if using jersey client.. add X here or
else things will break)

Regardless, I'll try latest and get back to you more specifically. maybe
this is a different issue.

**Comment by yurishkuro** [comment]
I agree, `peer.serviceName

**Comment by yurishkuro** [comment]
released as 0.8.1
