### ISSUE TITLE
Test classes are in release jars

### ISSUE THREAD

**Issue by felixbarny** [uber/jaeger-client-java#48]
For example `jaeger-core-0.8.0.jar` contains the class `com.uber.jaeger.SpanTest` which seems a bit weird to me. Is this intended? I'd expect the test classes to be published in `jaeger-core-0.8.0-tests.jar` if they need to be published at all. See also https://discuss.gradle.org/t/how-to-reference-a-test-jar-from-a-project-in-a-multi-project-build/5715.

**Comment by yurishkuro** [comment]
Releasing as 0.8.2
