### ISSUE TITLE
Add findbugs and such to the build

### ISSUE THREAD

**Issue by yurishkuro** [uber/jaeger-client-java#56]
eg. https://github.com/openzipkin/zipkin/pull/1166

**Comment by vprithvi** [comment]
This seems pretty simple to add to the build with gradle https://github.com/tbroyer/gradle-errorprone-plugin

**Comment by vprithvi** [comment]
I looked into adding this, it's not as simple because jaeger-core contains generated sources which errorprone does not like. One way of resolving this would be to move the generated sources into it's own gradle subproject which is compiled by the regular java compiler.
