### ISSUE TITLE
Add instrumentation for Apache AsyncHttpClient

### ISSUE THREAD

**Issue by yurishkuro** [uber/jaeger-client-java#62]
We have users who use [Apache AsyncHttpClient](https://hc.apache.org/httpcomponents-asyncclient-dev/httpasyncclient/apidocs/org/apache/http/nio/client/HttpAsyncClient.html) instead of Dropwizard. We should have a module in jaeger to add tracing to that client.

**Comment by vprithvi** [comment]
I think we best way of adding this would be to use Apache's [RequestInterceptors](https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/HttpRequestInterceptor.html) and [ResponseInterceptors](https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/HttpResponseInterceptor.html)

**Comment by yurishkuro** [comment]
Perhaps. I didn't find where you can actually register those with http client.

We need to ensure the following:
 * the span is always finished regardless of the request success or failure. Can some earlier response interceptor prevent tracing interceptor from running?
 * the client-side span is stored somewhere. There are two options
   * push it to the stack of TracingContext - probably the best, provided response guarantee is satisfied. Also need to consider threading implications, since the API has a bunch of futures, need to ensure the response interceptor runs on the same thread, otherwise this approach won't work
   * store it in some request context - not sure how feasible, the first `execute` method does not seem to have access to any context

**Comment by vprithvi** [comment]
The way one would go about adding this to a HttpClient would look similar to the following code
```java
CloseableHttpAsyncClient client= HttpAsyncClients.custom()
                                   .addInterceptorFirst(new JaegerRequestInterceptor())
                                   .addInterceptorFirst(new JaegerResponseInterceptor())
                                   .build();

```
The `HttpClient` holds on to a list of request and response interceptors through a [HttpProcessor](https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/protocol/HttpProcessor.html). 
An earlier interceptor can prevent the execution of the tracing interceptor (and all other interceptors) by throwing an exception. Normal http failures like 4xx, 5xx response should be handled as expected. If the interceptors are collaborating with each other, one can have shared state to manage execution of filters by means of flags or such. 

As for your second concern, a place we can store this information is as part of the [HttpContext](https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/protocol/HttpContext.html). Both the request and response interceptor have `process(HttpRequest request, HttpContext context)` in their interface. This approach also means that we can rely on the Apache implementation to run both the interceptors on the same context.

**Comment by yurishkuro** [comment]
I'd say we can recommend people to add tracing interceptor as `first`, with explanation that it helps to capture errors in the response regardless of other interceptors. But we can't really requir that people do that, so - best effort.

+1 for HttpContext, I think it's better than pushing to the TraceContext stack, since the above caveat might cause the span not to be popped. It does mean that if there's any lower-level tracing instrumentation inside the http client it needs to know where to access the current span.

**Comment by vprithvi** [comment]
Sounds good. Getting the current span is abstracted by the use of `TraceUtils.getTraceContext()`. I'll have a preliminary PR up in a bit so that we can discuss on it
