### ISSUE TITLE
bug in logging http.url

### ISSUE THREAD

**Issue by adriancole** [uber/jaeger-client-java#70]
I'm not sure which side did this, but something in the jersey trace filter is printing a toString, not a url.

https://github.com/openzipkin/jaeger-jersey-example

```
      {
        "key": "http.url",
        "value": "org.glassfish.jersey.server.internal.routing.UriRoutingContext@20bca98f"
      },
      {
        "key": "http.url",
        "value": "http://localhost:9000/api"
      },
```

**Comment by yurishkuro** [comment]
@adriancole thanks for catching this.

@vprithvi can you take a look?

**Comment by vprithvi** [comment]
This is such a coincidence, I was just about to open a ticket for the same. It's incorrectly set in the filter, and has no tests. I'll fix it!
