### ISSUE TITLE
Anyway to provide a different SPAN_CONTEXT_KEY?

### ISSUE THREAD

**Issue by hzariv** [uber/jaeger-client-java#88]
Is there a way to replace SPAN_CONTEXT_KEY to something like "x-trace-id" or "jaeger-trace-id" instead of ""uber-trace-id"?

The following TextMapCodec doesn't seem to be pluggable.

public class TextMapCodec implements Injector<TextMap>, Extractor<TextMap> { 
     /** Key used to store serialized span context representation */ 
     private static final String SPAN_CONTEXT_KEY = "uber-trace-id";

**Comment by yurishkuro** [comment]
If you're interested in putting a pull request, I would suggest the following:
```java
TextMapCodec codec = TextMapCodec.builder()
    .withURLEncoding(true)
    .withSpanContextKey("jaeger-trace-id")
    .withBaggagePrefix("jaeger-baggage-")
    .build();
```

And a private constructor that accepts the builder `TextMapCodec.Builder`
