### ISSUE TITLE
figure out how to get remote addr from grizzly HttpServletRequest

### ISSUE THREAD

**Issue by vprithvi** [uber/jaeger-client-java#97]
@oibe Could you comment on this?. It's from https://github.com/uber/jaeger-client-java/blob/c06613116dcd0bead64ab79836471facfc75dcd5/jaeger-jaxrs2/src/main/java/com/uber/jaeger/filters/jaxrs2/ServerFilter.java#L59

**Comment by yurishkuro** [comment]
Closing in favor of #182
