### ISSUE TITLE
Insert debug origin header when debug is set

### ISSUE THREAD

**Issue by vprithvi** [uber/jaeger-client-java#98]
When a request is made with a debug header, set a `debug-origin` header that contains the name of the service that flipped the debug flag.

**Comment by yurishkuro** [comment]
do you mean the name of the service that sent an untraced request with debug header? If that service is known, it will be stored as a `peer.service` on the root span.

**Comment by vprithvi** [comment]
@yurishkuro Yes, the case I'm concerned about is when `Service A` is traced, but something makes a request to `A` with the debug header set.  
In todays world, unless all services in the chain are instrumented and reporting correctly, it is difficult to ascertain that this debug header originated in `A`. `peer.service` is only set when an inbound request has `X_UBER_SOURCE` header set, which is something that might not be true all the time (and perhaps none of the time for users that aren't uber).

**Comment by yurishkuro** [comment]
> it is difficult to ascertain that this debug header originated in A. 

Why is it difficult? Service `A` starts a root span in this case, with the debug flag stored on the span, and that span will also have the `jaeger-debug-id` tag populated.

**Comment by vprithvi** [comment]
I mentioned that it's difficult when the service isn't reporting or instrumented correctly. In that case we will not have the root span.

**Comment by yurishkuro** [comment]
You said service A is traced and someone makes a request to it with debug header. So A is instrumented and will create a root span. If it's not instrumented, then the debug header will be ignored altogether. If you have a different example, please outline it explicitly, with service names and their conditions.

**Comment by vprithvi** [comment]
I apologize for not providing enough details. 
The specific case is when `service A` is instrumented, but is not reporting. This can happen with mismatched thrift versions, or if an jaeger-agent is not running on hosts that the service is running on, or if somebody explicitly configured their service to use a NoopReporter.

**Comment by yurishkuro** [comment]
That feels like a completely random bandaid to a problem that has nothing to do with the tracer itself. Also, someone has to manually send a debug request to this service anyway, so they already know what it is. If it's not a manual request, then what is the problem you're trying to solve? Does it pass the test of 3?

**Comment by vprithvi** [comment]
Not yet. I'll close the issue.
